cairoshell/cairoshell

code/Cairo Desktop/Cairo Desktop.sln, code/Cairo Desktop/Cairo Desktop/App.xaml.cs, code/Cairo Desktop/Cairo Desktop/Cairo Desktop.csproj, code/Cairo Desktop/Cairo Desktop/Cairo.xaml, code/Cairo Desktop/Cairo Desktop/DesktopNavigationToolbar.xaml, code/Cairo Desktop/Cairo Desktop/DesktopNavigationToolbar.xaml.cs, code/Cairo Desktop/Cairo Desktop/MenuBar.xaml, code/Cairo Desktop/Cairo Desktop/MenuBar.xaml.cs, code/Cairo Desktop/Cairo Desktop/SupportingClasses/AppBarHelper.cs, code/Cairo Desktop/Cairo Desktop/Taskbar.xaml.cs, code/Cairo Desktop/Cairo Desktop/app.manifest, code/Cairo Desktop/CairoDesktop.Common/SystemFile.cs, code/Cairo Desktop/CairoDesktop.Interop/Shell.cs, code/Cairo Desktop/CairoDesktop.UWPInterop/StoreAppHelper.cs, code/Cairo Desktop/CairoDesktop.WindowsTasks/ApplicationWindow.cs, code/Installer/CairoShell_32.nsi, code/Installer/CairoShell_64.nsi
Fix crash window crash possibility, add logging for fullscreen events (#30), fix possible app grabber crash (#33), fix possible taskbar icon leaks, add Windows 10 Settings shortcut to Cairo menu (#32), add shortcut to all users start menu, improve icon thumbnails with high-dpi, add draggable desktop nav toolbar (#33)
=> Improvements for reported issues

Cairo Desktop/Cairo Desktop/Cairo.xaml.cs, Cairo Desktop/Cairo Desktop/Desktop.xaml, Cairo Desktop/Cairo Desktop/Desktop.xaml.cs, Cairo Desktop/Cairo Desktop/MenuBar.xaml.cs
I have added back the code to prevent win key repeats
I have implemented Alt+F4 on the Cairo Desktop
=> Multiple Resolution:  Issue #193 & Feature #200

Cairo Desktop/Cairo Desktop/Desktop.xaml.cs, Cairo Desktop/Cairo Desktop/MenuBar.xaml, Cairo Desktop/Cairo Desktop/MenuBar.xaml.cs, Cairo Desktop/CairoDesktop.Interop/Shell.cs
Desktop now checks style and tiling when drawing the wallpaper (When Cairo is shell)
Added code to detect if Cairo is set as system shell
Hid "Exit Cairo", when cairo is shell. Added logic to hide seperator if next to another seperator
=> Desktop wallpaper fix

Cairo Desktop/Cairo Desktop/Cairo Desktop.csproj, Cairo Desktop/Cairo Desktop/CairoWallpaperStyle.cs, Cairo Desktop/Cairo Desktop/Desktop.xaml.cs
Fixed stretching issue when wallpaper set to tiled.
Also added preliminary code for future handling of Cairo Background. Image, Color, Gradient and Video
=> Fixes bug in Tiled wallpaper mode

Cairo Desktop/Cairo Desktop/Desktop.xaml.cs, Cairo Desktop/CairoDesktop.Interop/NativeMethods.cs
Added the, apparently needed, Viewport settings to the imagebrush when Tile is set as the wallpaper mode. I tested with a 320px image.
Also added processing for when SPI_SETDESKWALLPAPER is recieved in WndProc
=> Figured out the tiling issue

Cairo Desktop/Cairo Desktop/Cairo Desktop.csproj, Cairo Desktop/Cairo Desktop/MenuBar.xaml.cs, Cairo Desktop/Cairo Desktop/MenuExtraClock.xaml.cs, Cairo Desktop/Cairo Desktop/MenuExtraSearch.xaml.cs, Cairo Desktop/Cairo Desktop/SupportingClasses/SystemHotKeys.cs, Cairo Desktop/Cairo Desktop/TaskButton.xaml.cs
https://support.microsoft.com/en-us/help/12445
=> Implemented various Explorer HotKeys based on

Cairo Desktop/Cairo Desktop/Cairo Desktop.csproj, Cairo Desktop/Cairo Desktop/DwmThumbnail.xaml, Cairo Desktop/Cairo Desktop/DwmThumbnail.xaml.cs, Cairo Desktop/Cairo Desktop/MenuBar.xaml.cs, Cairo Desktop/Cairo Desktop/SupportingClasses/AppBarHelper.cs, Cairo Desktop/Cairo Desktop/SupportingClasses/AppBarWindow.cs, Cairo Desktop/Cairo Desktop/SupportingClasses/FullScreenHelper.cs, Cairo Desktop/Cairo Desktop/SupportingClasses/WindowManager.cs, Cairo Desktop/Cairo Desktop/SystemTray.xaml.cs, Cairo Desktop/Cairo Desktop/TaskButton.xaml, Cairo Desktop/Cairo Desktop/TaskButton.xaml.cs, Cairo Desktop/Cairo Desktop/Taskbar.xaml.cs, Cairo Desktop/CairoDesktop.Interop/CairoDesktop.Interop.csproj, Cairo Desktop/CairoDesktop.Interop/NativeMethods.DwmApi.cs, Cairo Desktop/CairoDesktop.Interop/NativeMethods.User32.cs, Cairo Desktop/CairoDesktop.Interop/NativeMethods.cs, Cairo Desktop/CairoDesktop.WindowsTasks/WindowsTasksService.cs, Cairo Desktop/CairoDesktop.WindowsTray/NotificationArea.cs, Cairo Desktop/CairoDesktop.WindowsTray/NotifyIcon.cs
Refactored RECT. Created DwmThumbnailControl
Began implementing Taskbar Live Thumbnails
=> Added NativeMethod DWMApi.

Cairo Desktop/Cairo Desktop/Desktop.xaml.cs, Cairo Desktop/Cairo Desktop/MenuBar.xaml.cs, Cairo Desktop/Cairo Desktop/SupportingClasses/DesktopManager.cs
Also stop hiding Exit Cairo when debugging
=> When Cairo is set as shell, always show wallpaper (#408)

Cairo Desktop/Cairo Desktop/Welcome.xaml.cs
=> Fix for AppGrabberIssue

Cairo Desktop/Cairo Desktop/Cairo.xaml, Cairo Desktop/Cairo Desktop/DwmThumbnail.xaml.cs, Cairo Desktop/Cairo Desktop/TaskThumbWindow.xaml
- Added style to close button and made it theme-able
- DWM thumbnails now keep their aspect ratio, while remaining centered
=> Taskbar thumbnail tweaks

Cairo Desktop/Cairo Desktop/SupportingClasses/DesktopManager.cs
Attempt at fixing desktop toolbar sizing upon DPI changes on some machines
=> Recreate desktop toolbar when desktop recreated

Cairo Desktop/Cairo Desktop/Desktop.xaml.cs, Cairo Desktop/Cairo Desktop/Icon.xaml, Cairo Desktop/Cairo Desktop/Icon.xaml.cs, Cairo Desktop/Cairo Desktop/SupportingClasses/CustomCommands.cs
better filename selection when renaming on desktop.
Added some keyboard shortcuts
=> added features to Desktop

Cairo Desktop/Cairo Desktop/Cairo Desktop.csproj, Cairo Desktop/Cairo Desktop/MenuBar.xaml.cs, Cairo Desktop/Cairo Desktop/MenuBarShadow.xaml.cs, Cairo Desktop/Cairo Desktop/SupportingClasses/AppBarWindow.cs, Cairo Desktop/Cairo Desktop/SupportingClasses/DesktopManager.cs, Cairo Desktop/Cairo Desktop/SupportingClasses/ScreenSetupReason.cs, Cairo Desktop/Cairo Desktop/SupportingClasses/WindowManager.cs, Cairo Desktop/Cairo Desktop/SupportingClasses/WindowManagerEventArgs.cs, Cairo Desktop/CairoDesktop.Interop/NativeMethods.User32.cs
- Fixed menu bar shadow placement not matching menu bar
- Fixed taskbar placement with auto-hide (#429)
- Minor refactor to plumb screen setup reason through WindowManager events
=> Mixed DPI fixes

Cairo Desktop/Cairo Desktop/Cairo Desktop.csproj, Cairo Desktop/Cairo Desktop/StacksContainer.xaml, Cairo Desktop/Cairo Desktop/StacksContainer.xaml.cs, Cairo Desktop/Cairo Desktop/StacksScroller.xaml, Cairo Desktop/Cairo Desktop/StacksScroller.xaml.cs, Cairo Desktop/CairoDesktop.Common/SystemDirectory.cs
Directory files no longer enumerated until requested
Refactored stacks scroller into UserControl created upon stack opening
=> Lazy load stacks directory contents

Cairo Desktop/Cairo Desktop/DesktopNavigationToolbar.xaml, Cairo Desktop/Cairo Desktop/DesktopNavigationToolbar.xaml.cs, Cairo Desktop/Cairo Desktop/SupportingClasses/DesktopManager.cs, Cairo Desktop/CairoDesktop.Localization/DisplayString.cs, Cairo Desktop/CairoDesktop.Localization/Language.cs
Also did some minor refactoring and fixed error when exiting Cairo while desktop overlay is open
=> Add reset position option to desktop toolbar menu

Cairo Desktop/CairoDesktop.WindowsTray/CairoDesktop.WindowsTray.csproj, Cairo Desktop/CairoDesktop.WindowsTray/Delegates.cs, Cairo Desktop/CairoDesktop.WindowsTray/ExplorerTrayService.cs, Cairo Desktop/CairoDesktop.WindowsTray/NotificationArea.cs, Cairo Desktop/CairoDesktop.WindowsTray/NotifyIcon.cs, Cairo Desktop/CairoDesktop.WindowsTray/SafeNotifyIconData.cs, Cairo Desktop/CairoDesktop.WindowsTray/TrayService.cs
Tray now still works even if Explorer is misbehaving
=> Minor tray refactor, improve error handling

Cairo Desktop/Cairo Desktop/CairoSettingsWindow.xaml, Cairo Desktop/Cairo Desktop/CairoSettingsWindow.xaml.cs, Cairo Desktop/Cairo Desktop/MenuBar.xaml.cs, Cairo Desktop/Cairo Desktop/MenuBarShadow.xaml.cs, Cairo Desktop/Cairo Desktop/SupportingClasses/AppBarWindow.cs, Cairo Desktop/Cairo Desktop/SystemTray.xaml.cs, Cairo Desktop/Cairo Desktop/Taskbar.xaml.cs, Cairo Desktop/Extensions/CairoDesktop.Extensions.SystemMenuExtras/SystemTray.xaml.cs
- Show notification area icons
- Show hibernate option in Cairo menu
- Enable menu bar shadow
- Programs menu layout
- Taskbar display mode
=> Make more setting changes work without restart

Cairo Desktop/CairoDesktop.WindowsTray/NotificationArea.cs, Cairo Desktop/CairoDesktop.WindowsTray/TrayService.cs
- Fixes Open Hardware Monitor
- Adds tray icons to Explorer when exiting Cairo
=> More tray compat

Cairo Desktop/Cairo Desktop/App.xaml.cs, Cairo Desktop/Cairo Desktop/TaskButton.xaml.cs, Cairo Desktop/Cairo Desktop/TaskThumbWindow.xaml.cs, Cairo Desktop/Cairo Desktop/Taskbar.xaml.cs, Cairo Desktop/CairoDesktop.AppGrabber/AppGrabber.cs, Cairo Desktop/CairoDesktop.AppGrabber/CairoDesktop.AppGrabber.csproj, Cairo Desktop/CairoDesktop.AppGrabber/QuickLaunchManager.cs, Cairo Desktop/CairoDesktop.AppGrabber/TaskCategoryProvider.cs, Cairo Desktop/CairoDesktop.Common/DesignPatterns/SingletonObject.cs, Cairo Desktop/CairoDesktop.WindowsTasks/ApplicationWindow.cs, Cairo Desktop/CairoDesktop.WindowsTasks/CairoDesktop.WindowsTasks.csproj, Cairo Desktop/CairoDesktop.WindowsTasks/ITaskCategoryProvider.cs, Cairo Desktop/CairoDesktop.WindowsTasks/TaskCategoryChangeDelegate.cs, Cairo Desktop/CairoDesktop.WindowsTasks/Tasks.cs, Cairo Desktop/CairoDesktop.WindowsTasks/TasksService.cs, Cairo Desktop/CairoDesktop.WindowsTasks/WindowsTasksService.cs, Cairo Desktop/CairoDesktop.WindowsTray/ExplorerTrayService.cs, Cairo Desktop/CairoDesktop.WindowsTray/NotificationArea.cs, Cairo Desktop/CairoDesktop.WindowsTray/TrayService.cs
Did some additional refactoring as well.
=> Stop referencing AppGrabber from WindowsTasks

Cairo Desktop/Cairo Desktop/Cairo Desktop.csproj, Cairo Desktop/Cairo Desktop/Cairo.xaml, Cairo Desktop/Cairo Desktop/Cairo.xaml.cs, Cairo Desktop/Cairo Desktop/MenuExtraSearch.xaml, Cairo Desktop/Cairo Desktop/Taskbar.xaml, Cairo Desktop/Cairo Desktop/Welcome.xaml, Cairo Desktop/Extensions/CairoDesktop.Extensions.SystemMenuExtras/Search.xaml
Now it is easier for a theme to specify a different font family or font size.
=> Customizable fonts

Cairo Desktop/Cairo Desktop/Desktop.xaml.cs, Cairo Desktop/Cairo Desktop/Taskbar.xaml.cs
Fix crash on startup when overlapping taskbar enabled. Temp fix, better fix in DI branch
Fix taskbar position settings not causing desktop adjustment when overlapping taskbar enabled
=> Fixed issues with overlapping taskbar option

Cairo Desktop/Cairo Desktop/Cairo Desktop.csproj, Cairo Desktop/Cairo Desktop/CairoApplication.InitializationRoutines.cs, Cairo Desktop/Cairo Desktop/CairoApplication.xaml.cs, Cairo Desktop/Cairo Desktop/Desktop.xaml.cs, Cairo Desktop/Cairo Desktop/DesktopOverlay.xaml.cs, Cairo Desktop/Cairo Desktop/MenuBar.xaml.cs, Cairo Desktop/Cairo Desktop/SupportingClasses/AppBarEventArgs.cs, Cairo Desktop/Cairo Desktop/SupportingClasses/AppBarEventReason.cs, Cairo Desktop/Cairo Desktop/SupportingClasses/AppBarHelper.cs, Cairo Desktop/Cairo Desktop/SupportingClasses/AppBarWindow.cs, Cairo Desktop/Cairo Desktop/SupportingClasses/AppBarWindowService.cs, Cairo Desktop/Cairo Desktop/SupportingClasses/DesktopManager.cs, Cairo Desktop/Cairo Desktop/SupportingClasses/IWindowService.cs, Cairo Desktop/Cairo Desktop/SupportingClasses/MenuBarWindowService.cs, Cairo Desktop/Cairo Desktop/SupportingClasses/TaskbarWindowService.cs, Cairo Desktop/Cairo Desktop/SupportingClasses/WindowManager.cs, Cairo Desktop/Cairo Desktop/Taskbar.xaml.cs
Use DI for AppBar windows rather than manually instantiating them.
Plans to extract AppBar logic will occur within ManagedShell.
=> Window management rework

.github/workflows/build.yml, Cairo Desktop/Cairo Desktop/CairoApplication.xaml.cs, Cairo Desktop/Cairo Desktop/MenuExtraSearch.xaml.cs, Cairo Desktop/Cairo Desktop/SupportingClasses/EnumUtility.cs, Installer/CairoShell_32.nsi, Installer/CairoShell_64.nsi
- Fix exit code was 0 instead of 1 when shell
- Fix build warnings, add logging
- Set installer version, update uninstall prompt
=> Post DI fixes

Cairo Desktop/Cairo Desktop/Cairo Desktop.csproj, Cairo Desktop/Cairo Desktop/CairoApplication.xaml.cs, Cairo Desktop/Cairo Desktop/Services/ThemeService.cs, Cairo Desktop/Cairo Desktop/Themes/Cairo.xaml, Cairo Desktop/Cairo Desktop/Themes/White.xaml, Cairo Desktop/CairoDesktop.Application/Interfaces/ICairoApplication.cs, Cairo Desktop/CairoDesktop.Common/CairoDesktop.Common.csproj
Also added method to ICairoApplication so that services can access theme properties
=> Add theme support for dark mode shell context menus

Cairo Desktop/Cairo Desktop/Taskbar.xaml, Cairo Desktop/CairoDesktop.AppGrabber/TaskCategoryProvider.cs
- Fix error on task list right-click due to unset ParentTaskbar
- Improve task categorization by reducing false matches
=> Fix some taskbar issues

Cairo Desktop/Cairo Desktop/Cairo Desktop.csproj, Cairo Desktop/CairoDesktop.AppGrabber/AppGrabberService.cs, Cairo Desktop/CairoDesktop.AppGrabber/AppGrabberUIResources.xaml.cs, Cairo Desktop/CairoDesktop.AppGrabber/ApplicationInfo.cs, Cairo Desktop/CairoDesktop.Common/CairoDesktop.Common.csproj
Takes advantage of the ManagedShell updates for #531.
=> Store app refactor

Cairo Desktop/Cairo Desktop/Cairo Desktop.csproj, Cairo Desktop/Cairo Desktop/Taskbar.xaml.cs, Cairo Desktop/CairoDesktop.AppGrabber/TaskCategoryProvider.cs, Cairo Desktop/CairoDesktop.Common/CairoDesktop.Common.csproj
Detect category by comparing ProcId of already open windows with new window
Detect category by comparing executable (adds category detection when application is launched via symlink, for example scoop apps)
=> Improve application category detection

Cairo Desktop/Cairo Desktop/Services/DesktopManager.cs
Fixes https://github.com/cairoshell/cairoshell/issues/567
=> Don't toggle Desktop icons when Dynamic Desktop is not enabled

Cairo Desktop/CairoDesktop.AppGrabber/TaskCategoryProvider.cs
This fixes a > 1 sec hang on my machine the first time this method is invoked (subsequent calls didn't seem to hang).
=> Make SameFile task category fetch async to fix hang

Cairo Desktop/Cairo Desktop/Cairo Desktop.csproj, Cairo Desktop/Cairo Desktop/SettingsUI.xaml, Cairo Desktop/Cairo Desktop/TaskButton.xaml, Cairo Desktop/Cairo Desktop/TaskButton.xaml.cs, Cairo Desktop/CairoDesktop.Common/CairoDesktop.Common.csproj, Cairo Desktop/CairoDesktop.Configuration/Properties/Settings.Designer.cs, Cairo Desktop/CairoDesktop.Configuration/Properties/Settings.settings, Cairo Desktop/CairoDesktop.Configuration/Settings.cs, Cairo Desktop/CairoDesktop.Configuration/app.config, Cairo Desktop/CairoDesktop.Localization/DisplayString.cs, Cairo Desktop/CairoDesktop.Localization/Language.cs
=> Adds support for task badges from ManagedShell 0.0.92

Cairo Desktop/Cairo Desktop/CairoApplication.xaml.cs, Cairo Desktop/Cairo Desktop/CairoApplicationInitializationService.InitializationRoutines.cs, Cairo Desktop/Cairo Desktop/Program.cs, Cairo Desktop/Cairo Desktop/Services/CairoApplicationThemeService.cs, Cairo Desktop/Cairo Desktop/Services/SettingsUIService.cs, Cairo Desktop/Cairo Desktop/SettingsUI.xaml.cs, Cairo Desktop/CairoDesktop.Application/Interfaces/ICairoApplication.cs, Cairo Desktop/CairoDesktop.Application/Interfaces/IInitializationService.cs, Cairo Desktop/CairoDesktop.Application/Interfaces/IThemeService.cs
-Created IThemeService.
-Refactored usage.
-Removed circular dependency when creating ThemeService and CairoApplication.
=> Theme Service Refactor

Cairo Desktop/Cairo Desktop/CairoApplication.xaml.cs, Cairo Desktop/Cairo Desktop/Desktop.xaml.cs, Cairo Desktop/Cairo Desktop/DesktopIcons.xaml.cs, Cairo Desktop/Cairo Desktop/DesktopNavigationToolbar.xaml.cs, Cairo Desktop/Cairo Desktop/DesktopOverlay.xaml.cs, Cairo Desktop/Cairo Desktop/Interfaces/IDesktopManager.cs, Cairo Desktop/Cairo Desktop/Program.cs, Cairo Desktop/Cairo Desktop/Services/DesktopManager.cs, Cairo Desktop/Cairo Desktop/Services/ShellHotKeyService.cs, Cairo Desktop/Cairo Desktop/Services/TaskbarWindowService.cs, Cairo Desktop/Cairo Desktop/Services/WindowManager.cs, Cairo Desktop/Cairo Desktop/SupportingClasses/FolderHelper.cs, Cairo Desktop/Cairo Desktop/Taskbar.xaml.cs
=> Implement IDesktopManager

Cairo Desktop/Cairo Desktop/Cairo Desktop.csproj, Cairo Desktop/Cairo Desktop/SupportingClasses/TaskbuttonStyleConverter.cs, Cairo Desktop/Cairo Desktop/Themes/Cairo.xaml, Cairo Desktop/Cairo Desktop/Themes/Fade.xaml, Cairo Desktop/Cairo Desktop/Themes/Flat.xaml, Cairo Desktop/Cairo Desktop/Themes/MiniMeow.xaml, Cairo Desktop/CairoDesktop.Common/CairoDesktop.Common.csproj
Rather than pulse the button forever (which is annoying), animate between task states, which will cause a similar effect for only the correct number of pulses.
=> Task flash changes

Cairo Desktop/Cairo Desktop/MenuBar.xaml.cs, Cairo Desktop/Cairo Desktop/Program.cs, Cairo Desktop/Cairo Desktop/Services/FirstRunService.cs, Cairo Desktop/Cairo Desktop/Services/MenuBarWindowService.cs, Cairo Desktop/Cairo Desktop/Services/SettingsUIService.cs, Cairo Desktop/Cairo Desktop/Services/TaskbarWindowService.cs, Cairo Desktop/Cairo Desktop/SettingsUI.xaml.cs, Cairo Desktop/Cairo Desktop/Taskbar.xaml.cs, Cairo Desktop/Cairo Desktop/Welcome.xaml.cs, Cairo Desktop/CairoDesktop.AppGrabber/AppGrabberService.cs, Cairo Desktop/CairoDesktop.AppGrabber/AppGrabberUI.xaml.cs, Cairo Desktop/CairoDesktop.AppGrabber/QuickLaunchManager.cs, Cairo Desktop/CairoDesktop.AppGrabber/TaskCategoryProvider.cs
Implimented  IAppGrabber and Refactored.
=> AppGrabber refactor

Cairo Desktop/Cairo Desktop/Icon.xaml.cs, Cairo Desktop/Cairo Desktop/TaskThumbWindow.xaml.cs
Fix task thumb window positioning on non-primary monitors
Fix image icon thumbnails with capital extension
=> Fix misc thumbnail issues

Cairo Desktop/Cairo Desktop/Cairo Desktop.csproj, Cairo Desktop/Cairo Desktop/DesktopNavigationToolbar.xaml.cs, Cairo Desktop/Cairo Desktop/SupportingClasses/CustomCommands.cs, Cairo Desktop/CairoDesktop.AppGrabber/AppGrabberService.cs, Cairo Desktop/CairoDesktop.Common/CairoDesktop.Common.csproj
Updated ManagedShell
Renamed pct to percent
Fixes #640.
=> Set working directory when opening items

Cairo Desktop/Cairo Desktop/Themes/Cairo.xaml, Cairo Desktop/Cairo Desktop/Themes/Flat.xaml
Override animations in the Flat theme so that everything doesn't need to be a gradient.
=> Fix errors during taskbar flash animation with Flat theme (#655)

Cairo Desktop/Cairo Desktop/Cairo Desktop.csproj, Cairo Desktop/Cairo Desktop/Taskbar.xaml, Cairo Desktop/Cairo Desktop/Taskbar.xaml.cs, Cairo Desktop/CairoDesktop.AppGrabber/QuickLaunchManager.cs, Cairo Desktop/CairoDesktop.Common/CairoDesktop.Common.csproj
- Fix quick launch and taskbar icons using old resolution when changing icon size
- Fix quick launch toolbar changes not causing taskbar to properly resize
=> Quick launch fixes

Cairo Desktop/CairoDesktop.Localization/Language.cs
Didn't notice that line was still in English last time, fixed it now.
=> Fixing a string on Brazilian Portuguese localization

Cairo Desktop/Cairo Desktop/TaskThumbnail.xaml.cs
Follows native Windows behavior.
=> Middle click to close window via thumbnail (#680)

Cairo Desktop/Cairo Desktop/SettingsUI.xaml, Cairo Desktop/Cairo Desktop/Taskbar.xaml.cs
Disable multimon settings when multimon disabled
Refresh taskbar when toggling multimon
=> Improvements to new taskbar settings

Cairo Desktop/Cairo Desktop/Cairo Desktop.csproj, Cairo Desktop/Cairo Desktop/MenuBar.xaml.cs, Cairo Desktop/Cairo Desktop/MenuBarShadow.xaml.cs, Cairo Desktop/Cairo Desktop/SupportingClasses/CairoAppBarWindow.cs, Cairo Desktop/Cairo Desktop/Taskbar.xaml.cs, Cairo Desktop/CairoDesktop.Common/CairoDesktop.Common.csproj
The ManagedShell improvements uncovered some existing issues in menu bar shadow and taskbar positioning.
=> Positioning fixes

Cairo Desktop/Cairo Desktop/Cairo Desktop.csproj, Cairo Desktop/Cairo Desktop/MenuBar.xaml.cs, Cairo Desktop/Cairo Desktop/ProgramsMenu.xaml.cs, Cairo Desktop/Cairo Desktop/Services/MenuBarWindowService.cs, Cairo Desktop/Cairo Desktop/SettingsUI.xaml, Cairo Desktop/Cairo Desktop/SupportingClasses/InvertBoolConverter.cs, Cairo Desktop/Cairo Desktop/Themes/Cairo.xaml, Cairo Desktop/CairoDesktop.Application/Interfaces/IMenuBar.cs, Cairo Desktop/CairoDesktop.Common/CairoDesktop.Common.csproj, Cairo Desktop/CairoDesktop.Configuration/Properties/Settings.Designer.cs, Cairo Desktop/CairoDesktop.Configuration/Properties/Settings.settings, Cairo Desktop/CairoDesktop.Configuration/Settings.cs, Cairo Desktop/CairoDesktop.Configuration/app.config, Cairo Desktop/CairoDesktop.Localization/DisplayString.cs, Cairo Desktop/CairoDesktop.Localization/Language.cs, Cairo Desktop/CairoDesktop.MenuBarExtensions/SystemTray.xaml.cs, Cairo Desktop/CairoDesktop.MenuBarExtensions/SystemTrayIcon.xaml.cs
- Updated ManagedShell
- Uses the ManagedShell auto-hide infrastructure to implement #120.
=> Menu bar auto-hide

Cairo Desktop/Cairo Desktop/MenuBarShadow.xaml.cs
Applies the same improvement that AppBars got in cairoshell/ManagedShell#77.
=> Improve shadow positioning

Cairo Desktop/Cairo Desktop/SettingsUI.xaml, Cairo Desktop/CairoDesktop.Common/Localization/DisplayString.cs, Cairo Desktop/CairoDesktop.Common/Localization/Language.cs
=> Fix copy/paste typo in a string name

Cairo Desktop/CairoDesktop.Common/Localization/Language.cs
I added the most recent strings and made a few corrections
=> Update Spanish translation

Cairo Desktop/Cairo Desktop/Cairo Desktop.csproj, Cairo Desktop/CairoDesktop.Common/CairoDesktop.Common.csproj, Cairo Desktop/CairoDesktop.Common/StacksManager.cs, Cairo Desktop/CairoDesktop.MenuBarExtensions/ActionCenter.xaml.cs, Cairo Desktop/CairoDesktop.Taskbar/SupportingClasses/TaskGroup.cs, Cairo Desktop/CairoDesktop.Taskbar/TaskButton.xaml.cs, Cairo Desktop/CairoDesktop.Taskbar/TaskThumbnail.xaml.cs
- The window minimize/restore animation now uses the Cairo taskbar button position
- Use immersive shell API to open Action Center
- Fix leak of TaskButtons
=> Use new ManagedShell features

Cairo Desktop/Cairo Desktop/Cairo Desktop.csproj, Cairo Desktop/CairoDesktop.Common/CairoDesktop.Common.csproj, Cairo Desktop/CairoDesktop.DynamicDesktop/Desktop.xaml.cs, Cairo Desktop/CairoDesktop.DynamicDesktop/DesktopOverlay.xaml.cs, Cairo Desktop/CairoDesktop.DynamicDesktop/Services/DesktopManager.cs, Cairo Desktop/CairoDesktop.Infrastructure/DependencyInjection/DependencyInjectionExtensions.cs, Cairo Desktop/CairoDesktop.Infrastructure/ObjectModel/AppBarEventArgs.cs, Cairo Desktop/CairoDesktop.Infrastructure/ObjectModel/AppBarEventReason.cs, Cairo Desktop/CairoDesktop.Infrastructure/ObjectModel/AppBarWindowService.cs, Cairo Desktop/CairoDesktop.Infrastructure/ObjectModel/CairoAppBarWindow.cs, Cairo Desktop/CairoDesktop.Infrastructure/ObjectModel/IWindowManager.cs, Cairo Desktop/CairoDesktop.Infrastructure/ObjectModel/WindowManagerEventArgs.cs, Cairo Desktop/CairoDesktop.Infrastructure/ObjectModel/WindowManagerEventReason.cs, Cairo Desktop/CairoDesktop.Infrastructure/Services/AppBarEventService.cs, Cairo Desktop/CairoDesktop.Infrastructure/Services/WindowManager.cs, Cairo Desktop/CairoDesktop.MenuBar/MenuBar.xaml.cs, Cairo Desktop/CairoDesktop.MenuBar/Services/MenuBarWindowService.cs, Cairo Desktop/CairoDesktop.Taskbar/Services/TaskbarWindowService.cs, Cairo Desktop/CairoDesktop.Taskbar/Taskbar.xaml.cs
- Update ManagedShell and account for changes
- Reimplement items dropped by ManagedShell
- Use WorkArea change as notification to WindowManager
=> Update ManagedShell, misc fixes

Cairo Desktop/Cairo Desktop/SettingsUI.xaml.cs, Cairo Desktop/CairoDesktop.AppGrabber/AppGrabberUI.xaml.cs, Cairo Desktop/CairoDesktop.AppGrabber/Category.cs, Cairo Desktop/CairoDesktop.Common/CairoMessageImageConverter.cs, Cairo Desktop/CairoDesktop.Common/KeyboardUtilities.cs, Cairo Desktop/CairoDesktop.Common/MessageBoxButtonConverter.cs, Cairo Desktop/CairoDesktop.DynamicDesktop/Desktop.xaml.cs
Found few typos.
https://github.com/crate-ci/typos
=> Correct misspellings

.github/workflows/build.yml
Replace complicated conditions with straight-forward matrix variables.
=> Make use of GHA matrix feature
