cairoshell/cairoshell

Cairo Desktop/Cairo Desktop/CairoSettingsWindow.xaml
Cairo Desktop/Cairo Desktop/MenuBar.xaml.cs
Cairo Desktop/Cairo Desktop/SupportingClasses/AppBarWindow.cs
Cairo Desktop/Cairo Desktop/Taskbar.xaml.cs
Cairo Desktop/CairoDesktop.Interop/Shell.cs

This addresses #404 for the full-width appearance and also removes the need to restart Cairo when changing the blur setting.

Taskbar blur

---

Cairo Desktop/Cairo Desktop/SupportingClasses/AppBarWindow.cs
Cairo Desktop/Cairo Desktop/SupportingClasses/DesktopManager.cs
Cairo Desktop/Cairo Desktop/SupportingClasses/WindowManager.cs
Cairo Desktop/Cairo Desktop/Taskbar.xaml.cs

Added notification to WindowManager for DWM restarts. Screen event windows trigger the notification. DesktopManager listens for the notification to redraw the desktop in the case where we are a child of Program Manager, when the Desktop window doesn't receive the window message.
Also fixed a hole in the per-monitor DPI change handling logic when only the taskbar and not menu bar is configured to appear on multiple monitors. Now the taskbars can be screen event windows in this case so that per-monitor DPI change messages are received.

Handle DWM restart

---

Cairo Desktop/Cairo Desktop/SupportingClasses/DesktopManager.cs

Without this fix, we attempt to add the desktop icons control to the new desktop window, even though it is already part of the overlay window, causing an error.

Fix crash when recreating desktop window while overlay is open

---

Cairo Desktop/Cairo Desktop/App.xaml.cs
Cairo Desktop/Cairo Desktop/CairoSettingsWindow.xaml.cs
Cairo Desktop/Cairo Desktop/MenuBar.xaml.cs
Cairo Desktop/Cairo Desktop/Startup.InitializationRoutines.cs
Cairo Desktop/Cairo Desktop/Startup.cs
Cairo Desktop/Cairo Desktop/SupportingClasses/AppBarHelper.cs
Cairo Desktop/Cairo Desktop/SupportingClasses/AppBarWindow.cs
Cairo Desktop/Cairo Desktop/SupportingClasses/UpdateManager.cs
Cairo Desktop/Cairo Desktop/SupportingClasses/WindowManager.cs
Cairo Desktop/Cairo Desktop/Taskbar.xaml.cs
Cairo Desktop/Cairo Desktop/Welcome.xaml.cs
Cairo Desktop/CairoDesktop.WindowsTasks/WindowsTasksService.cs

Allows us to keep track of Explorer taskbar state and restore it on exit (#320)

Refactor exit logic to occur in all graceful exit scenarios

---

Cairo Desktop/Cairo Desktop/SupportingClasses/DesktopManager.cs

The desktop overlay takes 2 frames to close while the icons control migrates, and holding the hotkey previously caused this to race with the overlay toggle. Now changing the overlay state while it is in the process of closing is basically a no-op.

Fix crash on Win-Shift-D

---

Cairo Desktop/CairoDesktop.Interop/NativeMethods.User32.cs
Cairo Desktop/CairoDesktop.Interop/NativeMethods.cs
Cairo Desktop/CairoDesktop.Interop/Shell.cs
Cairo Desktop/CairoDesktop.WindowsTray/CairoDesktop.WindowsTray.csproj
Cairo Desktop/CairoDesktop.WindowsTray/ExplorerTrayService.cs
Cairo Desktop/CairoDesktop.WindowsTray/NotificationArea.cs
Cairo Desktop/CairoDesktop.WindowsTray/SysTrayObject.cs
Cairo Desktop/CairoDesktop.WindowsTray/TrayNotify.cs

This PR will get the icons that Explorer is currently displaying to seed our notification area. This is needed because some apps don't respond correctly to the TaskbarCreated message we emit upon creating our notification area, so we miss those icons. Some examples this fixes are the Bluetooth icon, Nvidia, and Wireguard.
When we are running as shell, this is not an issue, because we will run before these apps launch.

Scrape Explorer tray for icons which don't respond to TaskbarCreated 

---

Cairo Desktop/Cairo Desktop/CairoSettingsWindow.xaml.cs
Cairo Desktop/Cairo Desktop/MenuBar.xaml.cs
Cairo Desktop/CairoDesktop.Configuration/Properties/Settings.Designer.cs
Cairo Desktop/CairoDesktop.Configuration/Properties/Settings.settings
Cairo Desktop/CairoDesktop.Configuration/app.config
Cairo Desktop/CairoDesktop.Interop/NativeMethods.User32.cs
Cairo Desktop/CairoDesktop.WindowsTray/ExplorerTrayService.cs
Cairo Desktop/CairoDesktop.WindowsTray/NotificationArea.cs
Cairo Desktop/CairoDesktop.WindowsTray/NotifyIcon.cs
Cairo Desktop/CairoDesktop.WindowsTray/TrayService.cs
Cairo Desktop/Extensions/CairoDesktop.Extensions.SystemMenuExtras/VolumeMenuExtra.cs

- Improve handling of NotifyIcon hidden state
- Only use the `dwState` value if `NIF_STATE` is specified. Also add hidden icons to our collection so that we have their existing properties in case they become visible.
- This fixes Pantherbar (#265) and other apps that use the [Hardcodet.NotifyIcon.Wpf library](https://github.com/hardcodet/wpf-notifyicon).
- Fix system volume tray icon
- This icon wasn't working previously because it requires `Shell_TrayWnd` to be topmost when the icon is clicked, so now we do that.
- The volume menu extra will now only appear for users on Windows 10 with Cairo running as shell, due to the UWP popup of the native icon being unusable in this configuration.
- Set HIWORD of v4 notify icon window messages to icon `UID`
- This fixes Avast apps (#351) and the …

Improve NotifyIcon compatibility

---

Cairo Desktop/Cairo Desktop/SupportingClasses/FullScreenHelper.cs
Cairo Desktop/CairoDesktop.Interop/NativeMethods.User32.cs

This fixes a couple problems and should at least partially #468.
- Allow windows with WS_CAPTION and/or WS_THICKFRAME to be considered full-screened. This fixes Chromium-based apps.
- If window has WS_CAPTION and WS_THICKFRAME, use the client rect instead of the window rect to determine if the window is full-screened.

Relax fullscreen app restrictions

---

Cairo Desktop/CairoDesktop.WindowsTray/NotifyIcon.cs

I think this was wallpapering over another issue that has since been fixed in the tray-compat branch, and now as a result having this is actually regressing things. I haven't seen any negative effects from removing this.

Stop manually focusing tray icons; seems to do more harm than good now

---

Cairo Desktop/CairoDesktop.WindowsTray/NotifyIcon.cs
Cairo Desktop/CairoDesktop.WindowsTray/TrayService.cs

My previous PR regarding this forgot that we need to focus _something_, so now instead of making Shell_TrayWnd topmost, focus it. 2 birds, 1 LOC.

Fix tray focusing properly

---

Cairo Desktop/CairoDesktop.Common/Helpers/GroupPolicyManager.cs
Cairo Desktop/CairoDesktop.WindowsTray/NotificationArea.cs

(#484) Now provides the ability to hide the Windows native volume control via group policy
Also refactored the registry logic in GroupPolicyManager to be generic and reusable

Add support for HideSCAVolume group policy

---

Cairo Desktop/Cairo Desktop/Startup.cs
Cairo Desktop/CairoDesktop.Configuration/Properties/Settings.Designer.cs
Cairo Desktop/CairoDesktop.Configuration/Properties/Settings.settings
Cairo Desktop/CairoDesktop.Configuration/Settings.cs
Cairo Desktop/CairoDesktop.Configuration/app.config

This adds the ability for a user to completely disable the menu bar via editing the settings directly. This is to support a use-case that requires disabling most of the Cairo UI before instantiating alternate UI components.

Add support for disabling menu bar via settings.

---

Installer/CairoShell_32.nsi
Installer/CairoShell_64.nsi

This is required for the DI branch to install correctly. Should also mean future nuget includes or other DLL output changes no longer require install script changes.
Hopefully the new description for the option to set Cairo as shell makes the ramifications of doing so more obvious.

Use wildcards in installer, stronger language for shell option

---

Cairo Desktop/Cairo Desktop/CairoSettingsWindow.xaml
Cairo Desktop/Cairo Desktop/CairoSettingsWindow.xaml.cs
Cairo Desktop/Cairo Desktop/Icon.xaml.cs
Cairo Desktop/Cairo Desktop/QuickLaunchButton.xaml.cs
Cairo Desktop/Cairo Desktop/TaskButton.xaml
Cairo Desktop/Cairo Desktop/TaskButton.xaml.cs
Cairo Desktop/Cairo Desktop/Taskbar.xaml.cs
Cairo Desktop/CairoDesktop.AppGrabber/AppGrabber.cs
Cairo Desktop/CairoDesktop.AppGrabber/ApplicationInfo.cs
Cairo Desktop/CairoDesktop.Common/IconImageConverter.cs
Cairo Desktop/CairoDesktop.Common/IconSize.cs
Cairo Desktop/CairoDesktop.Common/SearchHelper.cs
Cairo Desktop/CairoDesktop.Common/SystemFile.cs
Cairo Desktop/CairoDesktop.Configuration/Properties/Settings.Designer.cs
Cairo Desktop/CairoDesktop.Configuration/Properties/Settings.settings
Cairo Desktop/CairoDesktop.Configuration/Settings.cs
Cairo Desktop/CairoDesktop.Configuration/app.config
Cairo Desktop/CairoDesktop.Localization/DisplayString.cs
Cairo Desktop/CairoDesktop.Localization/Language.cs
Cairo Desktop/CairoDesktop.WindowsTasks/ApplicationWindow.cs

Basically what the title says, the taskbar can get cluttered pretty quick with the labels. (issue #510)
I did some clean up on the hard coded icon sizes thought the solution, that explains why some many files were touched.
Gave it a shot here and it worked pretty well, let me know your thoughts.

Hide taskbar labels (issue #510)

---

Cairo Desktop/Cairo Desktop/MenuBar.xaml.cs
Cairo Desktop/Cairo Desktop/Taskbar.xaml
Cairo Desktop/Cairo Desktop/Taskbar.xaml.cs
Cairo Desktop/Cairo Desktop/Themes/Cairo.xaml

Added new theme-able resources:
MenuBarWindowStyleBackground
TaskBarWindowBackground
Refactored Taskbar.xaml to use new resource
For solid color in theme file:
```
<SolidColorBrush Color="#FF000000" x:Key="MenuBarWindowStyleBackground" />
<SolidColorBrush Color="#FF000000" x:Key="TaskBarWindowBackground" />
```
Also added ability to set AllowT via:
```
Required attribute on ResourceDictionary:
xmlns:system="clr-namespace:System;assembly=mscorlib"
<system:Boolean x:Key="MenuBarWindowAllowsTransparency">False</system:Boolean>
<system:Boolean x:Key="TaskBarWindowAllowsTransparency">False</system:Boolean>
```

Allow for Opaque Taskbar and Menubar

---

Cairo Desktop/Cairo Desktop/Cairo Desktop.csproj
Cairo Desktop/Cairo Desktop/SettingsUI.xaml
Cairo Desktop/Cairo Desktop/SettingsUI.xaml.cs
Cairo Desktop/Cairo Desktop/SupportingClasses/CairoAppBarWindow.cs
Cairo Desktop/Cairo Desktop/SupportingClasses/TaskGroup.cs
Cairo Desktop/Cairo Desktop/SupportingClasses/TaskGroupConverter.cs
Cairo Desktop/Cairo Desktop/SupportingClasses/TaskGroupSizeConverter.cs
Cairo Desktop/Cairo Desktop/SupportingClasses/TaskThumbOrientationConverter.cs
Cairo Desktop/Cairo Desktop/SupportingClasses/TaskbuttonStyleConverter.cs
Cairo Desktop/Cairo Desktop/TaskButton.xaml
Cairo Desktop/Cairo Desktop/TaskButton.xaml.cs
Cairo Desktop/Cairo Desktop/TaskThumbWindow.xaml
Cairo Desktop/Cairo Desktop/TaskThumbWindow.xaml.cs
Cairo Desktop/Cairo Desktop/TaskThumbnail.xaml
Cairo Desktop/Cairo Desktop/TaskThumbnail.xaml.cs
Cairo Desktop/Cairo Desktop/Taskbar.xaml
Cairo Desktop/Cairo Desktop/Taskbar.xaml.cs
Cairo Desktop/Cairo Desktop/Themes/Cairo.xaml
Cairo Desktop/CairoDesktop.Common/CairoDesktop.Common.csproj
Cairo Desktop/CairoDesktop.Localization/DisplayString.cs
Cairo Desktop/CairoDesktop.Localization/Language.cs

When enabled, and there are multiple windows associated to an app, the taskbar will display a single TaskButton bound to a TaskGroup rather than a group of multiple TaskButtons bound to individual ApplicationWindows.
TaskGroup is an object that contains a list of ApplicationWindows, and has the same properties as an ApplicationWindow for binding. Its icon and title comes not from a window but from the application the windows are from. Task progress is averaged across all windows in the group with progress, and the task overlay icon is used from the first window that has one (that is similar to the logic Windows uses from what I could tell).
TaskThumbWindow was refactored to support showing a collection of windows from the TaskGroup, by moving the thumbnail into a separate UserControl. …

Windows 7+ style task grouping

---

Cairo Desktop/Cairo Desktop/DesktopNavigationToolbar.xaml.cs

The current absolute positioning method can be annoying, as when screen sizes change (such as RDP), the toolbar ends up in the wrong place. By using percentages, this doesn't occur.
Note that I didn't add migration for the setting. Whatever is saved from the old absolute positioning scheme will fail the bounds check and result in the default position being used. When the user moves it back to the desired location, the percentage will save. @josuave does this sound OK? Adding migration didn't seem worth it here, but open to adding it if needed.

Use percentage for desktop toolbar positioning

---

Cairo Desktop/Cairo Desktop/Cairo Desktop.csproj
Cairo Desktop/Cairo Desktop/MenuBar.xaml.cs
Cairo Desktop/Cairo Desktop/ProgramsMenu.xaml.cs
Cairo Desktop/Cairo Desktop/QuickLaunchButton.xaml
Cairo Desktop/Cairo Desktop/QuickLaunchButton.xaml.cs
Cairo Desktop/Cairo Desktop/TaskButton.xaml.cs
Cairo Desktop/CairoDesktop.AppGrabber/AppGrabberService.cs
Cairo Desktop/CairoDesktop.AppGrabber/ApplicationInfo.cs
Cairo Desktop/CairoDesktop.AppGrabber/CategoryList.cs
Cairo Desktop/CairoDesktop.AppGrabber/QuickLaunchManager.cs
Cairo Desktop/CairoDesktop.Common/CairoDesktop.Common.csproj

- Refactored AppGrabberService to reduce nesting
- Saves if app allows run as admin to config file with migration process
- Fixed admin dialog not saving
- Fixed quick launch context menu not hiding admin option
- Fixed quick launch context menu not having run as user option
Fixes #605.

Allow running capable UWP apps as admin

---

Cairo Desktop/CairoDesktop.AppGrabber/CategoryList.cs

Fixes crash with a saved UWP app that no longer exists

Add null check to UWP admin migration (#644)

---

Cairo Desktop/Cairo Desktop/SupportingClasses/TaskGroup.cs

Occurs with file explorer in combined task group mode.

Fix stuck progress when window is destroyed before updating progress value

---

Cairo Desktop/Cairo Desktop/DesktopNavigationToolbar.xaml.cs

Allows going to, for example, `%localappdata%` from the desktop toolbar.

Expand environment variables in go to folder window

---

Cairo Desktop/Cairo Desktop/Taskbar.xaml
Cairo Desktop/Cairo Desktop/Themes/Cairo.xaml
Cairo Desktop/CairoDesktop.Localization/DisplayString.cs
Cairo Desktop/CairoDesktop.Localization/Language.cs
Cairo Desktop/CairoDesktop.MenuBarExtensions/NotificationBalloonTitleConverter.cs
Cairo Desktop/CairoDesktop.MenuBarExtensions/NotificationBalloonWidthConverter.cs
Cairo Desktop/CairoDesktop.MenuBarExtensions/SystemTray.xaml
Cairo Desktop/CairoDesktop.MenuBarExtensions/SystemTray.xaml.cs
Cairo Desktop/CairoDesktop.MenuBarExtensions/SystemTrayIcon.xaml
Cairo Desktop/CairoDesktop.MenuBarExtensions/SystemTrayIcon.xaml.cs

Currently, balloon notifications do not work at all while Cairo is running (#620). This adds support for those in Cairo.
This is an inline implementation of notification balloons. The idea is that notifications overlapping applications are annoying, and we're already taking up screen space, so let's use it to make things less annoying.
The balloon contents are previewed in the primary display's menu bar, next to the icon, with a dismiss button. There is an animation when the notification is shown and when hidden. Hovering the notification shows the full contents.
When the notification area is collapsed, icons with balloon notifications will be promoted to be shown next to the pinned icons.
A few ancillary changes in this PR:
- Matched taskbar animation easing to the new notification …

Balloon notifications support

---

Cairo Desktop/Cairo Desktop/Cairo Desktop.csproj
Cairo Desktop/Cairo Desktop/Program.cs
Cairo Desktop/CairoDesktop.Common/CairoDesktop.Common.csproj
Installer/CairoShell.nsi

- Double host shutdown timeout from default 5 seconds to 10. I was hitting this timeout from time to time.
- Fix installer not laying down config file which includes binding redirects, needed for Microsoft.Extensions.Hosting dependencies (made apparent after updating these libs)
- Update ManagedShell to fix desktop icons staying hidden after exit

Fix issues when exiting Cairo

---

Cairo Desktop/Cairo Desktop/MenuBar.xaml.cs
Cairo Desktop/Cairo Desktop/SettingsUI.xaml.cs
Cairo Desktop/CairoDesktop.Application/Interfaces/IApplicationUpdateService.cs
Cairo Desktop/CairoDesktop.Infrastructure/Services/WinSparkleUpdateService.cs

If you delete WinSparkle.dll, the updater options should go away.

Remove access to updater if it isn't available

---

Cairo Desktop/CairoDesktop.Common/FolderView.cs

In newer versions of Windows 11, the Desktop shell folder also enumerates the user folders that used to be displayed in This PC. One of these is Desktop, which is simply recursive, so we should hide it (along with the others, which our existing logic already handles well).

Hide recursive Desktop icon on Windows 11 insider

---

.github/workflows/build.yml

WinSparkle DLL is the wrong architecture in builds from `dotnet publish`.
Not-so-elegant fix for now to allow release.

Fix build platform

---

Cairo Desktop/Cairo Desktop/Cairo Desktop.csproj
Cairo Desktop/CairoDesktop.AppGrabber/AppGrabberService.cs
Cairo Desktop/CairoDesktop.AppGrabber/ApplicationInfo.cs
Cairo Desktop/CairoDesktop.Common/CairoDesktop.Common.csproj

Recently Windows has been packaging some inbox win32 apps such as Notepad and Paint, so we are launching them via AppUserModelId. However, the way we did this required explorer.exe to be running, even though these apps can run just fine without explorer.
This changes apps known to launch without explorer (Edge PWAs and FullTrust apps) to use the new activation method exposed by ManagedShell, so now they can launch without explorer. This doesn't change anything for sandboxed apps such as Calculator.
The reason sandboxed apps are still launched using the old method that requires explorer: Sandboxed apps still require explorer to run anyway, and app activation APIs hang for quite some time when trying to launch them, so the old method ultimately works better.
This fixes #734 which …

App activation

---

Cairo Desktop/Cairo Desktop/Taskbar.xaml.cs

When tasks are configured to display only on the same monitor as the window, screen changes can cause tasks to go missing due to having an invalid associated `hMonitor`. Show these on the primary screen taskbar so they aren't lost.

Fix missing tasks after screen change

---

Cairo Desktop/Cairo Desktop/Cairo Desktop.csproj
Cairo Desktop/Cairo Desktop/MenuBar.xaml.cs
Cairo Desktop/Cairo Desktop/SettingsUI.xaml
Cairo Desktop/Cairo Desktop/SettingsUI.xaml.cs
Cairo Desktop/Cairo Desktop/SupportingClasses/IntegerValidationRule.cs
Cairo Desktop/Cairo Desktop/TaskButton.xaml.cs
Cairo Desktop/Cairo Desktop/Taskbar.xaml.cs
Cairo Desktop/Cairo Desktop/Themes/Flat Accent.xaml
Cairo Desktop/CairoDesktop.Application/Interfaces/IMenuBar.cs
Cairo Desktop/CairoDesktop.Common/CairoDesktop.Common.csproj
Cairo Desktop/CairoDesktop.Configuration/Properties/Settings.Designer.cs
Cairo Desktop/CairoDesktop.Configuration/Properties/Settings.settings
Cairo Desktop/CairoDesktop.Configuration/Settings.cs
Cairo Desktop/CairoDesktop.Configuration/app.config
Cairo Desktop/CairoDesktop.Localization/DisplayString.cs
Cairo Desktop/CairoDesktop.Localization/Language.cs

- Added setting to control how long before an auto-hide appbar is shown while the mouse is on it, and made misc related updates
- Added logic to prevent multiple auto-hidden appbars on the same edge
- Added missing space to Flat Accent theme
- Re-enabled full-width taskbar blur when using the auto-hide setting, as now it works properly
- Updated ManagedShell

Add setting for auto-hide show delay

---

Cairo Desktop/Cairo Desktop/Services/AppBarWindowService.cs
Cairo Desktop/Cairo Desktop/Services/WindowManager.cs
Cairo Desktop/Cairo Desktop/SupportingClasses/WindowManagerEventArgs.cs

The screen device name changes with each new RDP connection to the machine. With the multi-mon options enabled, the device name mismatch was preventing us from finding a window to update screen information for when the fast path is being used.
This was easily triggered by connecting via RDP at one screen resolution, then disconnecting and connecting again with a different screen resolution.
I missed this in #770, as this is another item that was being papered over before.

Fix fast screen setup when device name changes

---

Cairo Desktop/Cairo Desktop/Taskbar.xaml.cs

Set the position when we open the menu rather than only when certain settings change.

Fix tasklist position out of sync

---

Cairo Desktop/Cairo Desktop/Cairo Desktop.csproj
Cairo Desktop/Cairo Desktop/CairoApplicationInitializationService.InitializationRoutines.cs
Cairo Desktop/Cairo Desktop/MenuBar.xaml
Cairo Desktop/Cairo Desktop/MenuBar.xaml.cs
Cairo Desktop/CairoDesktop.Common/CairoDesktop.Common.csproj
Cairo Desktop/CairoDesktop.Common/Logging/Other/ManagedShellLoggerProvider.cs
Cairo Desktop/CairoDesktop.Infrastructure/DependencyInjection/DependencyLoader.cs
Cairo Desktop/CairoDesktop.Infrastructure/Services/ExtensionService.cs

Improves the robustness of extension loading so that extensions throwing exceptions at startup don't prevent Cairo startup.
Also added a couple adjacent improvements:
- Fixed an old TODO where logs weren't emitted early on during startup
- Improved Cairo menu item extension insertion logic so that it's not sensitive to us adding/removing items

Catch extension load errors that could halt init

---

Cairo Desktop/Cairo Desktop/Taskbar.xaml.cs

The fix in #773 was incomplete--the filter was updated, but we didn't trigger a refresh so that the items would be re-filtered after a display change. This PR does that.

Actually fix missing taskbar items

---

Cairo Desktop/Cairo Desktop/MenuBar.xaml.cs
Cairo Desktop/Cairo Desktop/SettingsUI.xaml
Cairo Desktop/CairoDesktop.Common/Settings.cs

I've added the ability to toggle the Places and Programs option in the menu bar. I'd like to disable it as i don't really use it anyways and it takes up space for my _way too big_ tray.
I'm quite unfamiliar with the code base and just went off of how everything else, i think, is done.
For translations i'm just piggy backing off of the existing translations for the 2 options.
If i made a mistake or it's not up to standard then let me know.

Add togglable Places & Programs

---

Cairo Desktop/Cairo Desktop/CairoApplication.xaml.cs
Cairo Desktop/Cairo Desktop/Commands/OpenLocationCommand.cs
Cairo Desktop/Cairo Desktop/Commands/OpenLocationInWindowCommand.cs
Cairo Desktop/Cairo Desktop/Desktop.xaml.cs
Cairo Desktop/Cairo Desktop/DesktopIcons.xaml.cs
Cairo Desktop/Cairo Desktop/DesktopNavigationToolbar.xaml.cs
Cairo Desktop/Cairo Desktop/DesktopOverlay.xaml.cs
Cairo Desktop/Cairo Desktop/MenuBar.xaml.cs
Cairo Desktop/Cairo Desktop/Services/AppBarWindowService.cs
Cairo Desktop/Cairo Desktop/Services/DesktopManager.cs
Cairo Desktop/Cairo Desktop/Services/FirstRunService.cs
Cairo Desktop/Cairo Desktop/Services/MenuBarWindowService.cs
Cairo Desktop/Cairo Desktop/Services/SettingsUIService.cs
Cairo Desktop/Cairo Desktop/Services/TaskbarWindowService.cs
Cairo Desktop/Cairo Desktop/SettingsUI.xaml
Cairo Desktop/Cairo Desktop/SettingsUI.xaml.cs
Cairo Desktop/Cairo Desktop/Taskbar.xaml.cs
Cairo Desktop/Cairo Desktop/Welcome.xaml
Cairo Desktop/Cairo Desktop/Welcome.xaml.cs
Cairo Desktop/CairoDesktop.Infrastructure/Services/ShellManagerService.cs
Cairo Desktop/CairoDesktop.MenuBarExtensions/ActionCenterMenuBarExtension.cs
Cairo Desktop/CairoDesktop.MenuBarExtensions/Clock.xaml.cs
Cairo Desktop/CairoDesktop.MenuBarExtensions/ClockMenuBarExtension.cs
Cairo Desktop/CairoDesktop.MenuBarExtensions/MenuBarExtensionsShellExtension.cs
Cairo Desktop/CairoDesktop.MenuBarExtensions/SearchMenuBarExtension.cs
Cairo Desktop/CairoDesktop.MenuBarExtensions/SystemTray.xaml.cs
Cairo Desktop/CairoDesktop.MenuBarExtensions/SystemTrayMenuBarExtension.cs
Cairo Desktop/CairoDesktop.MenuBarExtensions/VolumeMenuBarExtension.cs

- Changed direct references of `Settings.Instance` to use the injected `Settings` instance where readily available to do so
- There are still a few direct references left that will become easier to change after future PRs.
- Simplified `SettingsUI` bindings by setting the `DataContext`
- Unrelated: Fixed mouse back/forward buttons navigating the desktop when the dynamic desktop is disabled.

Use injected settings more

---

Cairo Desktop/CairoDesktop.MenuBar/Converters/ProgramsMenuHeightConverter.cs
Cairo Desktop/CairoDesktop.MenuBar/ProgramsMenu.xaml

The programs menu normally changes its height depending on its contents. When the menu bar is on the bottom screen edge, and the menu shrinks due to selecting a smaller category, the clicked category moves out from under the cursor, causing the mouseup to occur outside of the menu, closing it.
Fixed the issue by making the programs menu a constant height when the menu bar is set to the bottom screen edge.

Fix bottom programs menu closing itself (#824)

---

Cairo Desktop/Cairo Desktop/Program.cs
Cairo Desktop/CairoDesktop.AppGrabber/AppGrabberService.cs
Cairo Desktop/CairoDesktop.AppGrabber/ApplicationInfo.cs
Cairo Desktop/CairoDesktop.AppGrabber/CairoDesktop.AppGrabber.csproj
Cairo Desktop/CairoDesktop.AppGrabber/CategoryList.cs
Cairo Desktop/CairoDesktop.AppGrabber/Commands/AddToProgramsCommand.cs
Cairo Desktop/CairoDesktop.AppGrabber/Commands/AddToQuickLaunchCommand.cs
Cairo Desktop/CairoDesktop.Common/Icon.xaml.cs
Cairo Desktop/CairoDesktop.Common/Localization/DisplayString.cs
Cairo Desktop/CairoDesktop.Common/Localization/Language.cs

- Added "add to programs menu" and "add to quick launch" commands to the shell context menu
- If a shortcut that was added has been deleted but the target still exists, use the target where possible
- This is useful if you "add to programs" a shortcut from your desktop, then delete it from your desktop
- Fixed being unable to drag desktop icons to the programs menu
- Adding exe files without a file description no longer throws an error

Misc App Grabber improvements

---

Cairo Desktop/CairoDesktop.MenuBar/MenuBar.xaml.cs

Restored some logic that I inadvertently removed when I rewrote the Cairo menu.

Restore separator deduplication logic

---

Cairo Desktop/Cairo Desktop/SettingsUI.xaml.cs
Cairo Desktop/Cairo Desktop/SupportingClasses/ExePath.cs

Otherwise we get the DLL instead of the EXE.
Fixes #857

Fix autorun setting on .NET 6

---

Cairo Desktop/Cairo Desktop/Cairo Desktop.csproj
Cairo Desktop/CairoDesktop.Common/CairoDesktop.Common.csproj
Cairo Desktop/CairoDesktop.Common/Logging/Other/ManagedShellLoggerProvider.cs

Updates ManagedShell to fix #398 and other issues
Improved ManagedShellLoggerProvider to not crash in the case the file could not be created, and moved it away from using Debug.WriteLine now that we have log flushing

Update ManagedShell, improve logger

---

Cairo Desktop/Cairo Desktop/SupportingClasses/FilePathValidationRule.cs

The settings window was marking the default value as invalid. The validator wasn't expanding environment variables, which the default setting contains.

Fix unable to restore default file manager

---

Cairo Desktop/CairoDesktop.AppGrabber/AppGrabberUI.xaml
Cairo Desktop/CairoDesktop.AppGrabber/AppGrabberUI.xaml.cs
Cairo Desktop/CairoDesktop.AppGrabber/Commands/OpenAppGrabberCommand.cs

When opening the App Grabber from a menu bar on a non-primary display, the size was being set incorrectly based on the primary display instead.

Fix App Grabber size on secondary display

---

Cairo Desktop/Cairo Desktop/SettingsUI.xaml
Cairo Desktop/Cairo Desktop/SettingsUI.xaml.cs
Cairo Desktop/CairoDesktop.Common/Localization/DisplayString.cs
Cairo Desktop/CairoDesktop.Common/Localization/Language.cs
Cairo Desktop/CairoDesktop.Common/Settings.cs
Cairo Desktop/CairoDesktop.MenuBar/MenuBar.xaml.cs

Our WinKey handling prevents other WinKey shortcuts throughout the system from working properly. Allow users to disable it if they want to.
Fixes #713

Allow disabling the WinKey when shell

---

Cairo Desktop/Cairo Desktop/Cairo Desktop.csproj
Cairo Desktop/CairoDesktop.AppGrabber/AppGrabberTaskCategoryProvider.cs
Cairo Desktop/CairoDesktop.AppGrabber/CategoryList.cs
Cairo Desktop/CairoDesktop.Common/CairoDesktop.Common.csproj
Cairo Desktop/CairoDesktop.Common/NavigationManager.cs
Cairo Desktop/CairoDesktop.DynamicDesktop/DesktopIcons.xaml
Cairo Desktop/CairoDesktop.DynamicDesktop/DesktopIcons.xaml.cs
Cairo Desktop/CairoDesktop.DynamicDesktop/Services/DesktopManager.cs
Cairo Desktop/CairoDesktop.MenuBarExtensions/Clock.xaml
Cairo Desktop/CairoDesktop.MenuBarExtensions/Clock.xaml.cs
Cairo Desktop/CairoDesktop.MenuBarExtensions/Search.xaml
Cairo Desktop/CairoDesktop.MenuBarExtensions/Search.xaml.cs
Cairo Desktop/CairoDesktop.Taskbar/QuickLaunchButton.xaml
Cairo Desktop/CairoDesktop.Taskbar/QuickLaunchButton.xaml.cs
Cairo Desktop/CairoDesktop.Taskbar/Services/TaskbarWindowService.cs
Cairo Desktop/CairoDesktop.Taskbar/TaskButton.xaml.cs
Cairo Desktop/CairoDesktop.Taskbar/Taskbar.xaml
Cairo Desktop/CairoDesktop.Taskbar/Taskbar.xaml.cs

Throughout the application lifecycle, we may close or open these windows for various reasons (display changes, preference changes, etc). Unfortunately, previously these windows would always remain in memory after being closed, for multiple reasons. The changes in this PR plug the leaks that were causing this to happen.
- Fixed event handler and timer leaks in Clock and Search menu bar extras
- Fixed AppBarWindow leak via ManagedShell update
- Fixed NavigationManager never being disposed
- Fixed event handler leak in DesktopIcons and NavigationManager
- Multiple fixes for AppGrabberTaskCategoryProvider
- Fixed the taskbar creating multiple instances of the provider, when only one is needed at a time, by moving the logic to TaskbarWindowService
- Fixed event handler leaks in the class
- …

Fix leaks causing menu bar, taskbar, and desktop instances to be retained in memory
